name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install requirements
      run: pip install -r .binder/requirements.txt
    - name: Install pytest-cov
      run: pip install pytest-cov
    - name: Run tests and collect coverage
      run: pytest --cov=sklearn sklearn/tests/
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
